version: '3.9'
services:
  authentication-service:
    image: authentication_image
    container_name: authenticationcontainer2
    build: demoAuthentication/
    restart: always
    networks:
      - mynetwork
    ports:
      - 8087:8087
    depends_on:
      - mysqlService
      - apigateway

  music-service:
    image: music_image
    container_name: trackingservice
    build: BEJ_C3_S3_Containerize_Using_Docker_Compose_MC_1/
    restart: always
    networks:
      - mynetwork
    ports:
      - 64300:64300
    depends_on:
      - mongoService
      - apigateway

  mysqlService:
    image: mysql:latest
    container_name: mysqlcontainer4
    networks:
      - mynetwork
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  mongoService:
      image: mongo
      container_name: mongocontainer4
      ports:
        - 27017:27017
      networks:
        - mynetwork


  apigateway:
    container_name: spring-cloud-api-gateway2
    build: springCloudApiGateway/
    networks:
      - mynetwork
    ports:
      - "9002:9002"

networks:
  mynetwork:
    driver: bridge





