FROM openjdk
WORKDIR usr/src
ADD ./target/springCloudApiGateway-0.0.1-SNAPSHOT.jar /usr/src/springCloudApiGateway-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","springCloudApiGateway-0.0.1-SNAPSHOT.jar"]